dist: xenial
language: python
python:
  - "3.7"

install:
  - pip install nbfancy 
  - pip install -e .

script:
  - nbfancy configure -y jupyter_css 
  - nbfancy rerun --allow_errors
  - nbfancy render
  - nbfancy html

deploy:
  provider: pages
  repo: bath-lessons/funcs-classes-python
  target-branch: gh-pages
  local-dir: html
  github_token: $GITHUB_TOKEN
  skip-cleanup: true
  on:
    branch: master
    python: 3.7
